version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - mongo
  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redisdata:/data'
  mongo:
    container_name: 'mongo'
    image: 'mongo:3.3'
    command: '--storageEngine wiredTiger'
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - 'mongodata:/data/db'

volumes:
  redisdata:
  mongodata: